# Common JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use Render's DATABASE_URL environment variable
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=1234567890
jwt.expiration=86400000








# spring.application.name=food_adda
# server.port=8080

# # PostgreSQL Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/food_adda_db
# spring.datasource.username=postgres
# # spring.datasource.username=root
# spring.datasource.password=Mallidhanu@439
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA/Hibernate Configuration
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# # JWT Configuration
# jwt.secret=your_jwt_secret_key_change_this_in_production_environment_with_a_strong_key
# jwt.expiration=86400000

# # Server Configuration
# server.servlet.context-path=/api
# spring.application.display-name=Food Adda Restaurant Management System
